version: "3.8"

services:
  # docker exec -it next-13-app /bin/bash
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    container_name: next-13-app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

